export const aboutus =[ 
    {
        name: "Alexandre Becker",
        link: "http://lattes.cnpq.br/0107630830900915",
        bio: "Mestrando em Economia Política Mundial na UFABC, Bacharel em Ciência e Tecnologia e Bacharel em Neurociências pela mesma instituição.",
        photo: "",
    },
    {
        name: "Alexis Saludjian",
        link: "http://lattes.cnpq.br/5913369787997553",
        bio: "Economia UFRJ. Crescimento e Desenvolvimento Econômico, e Economia Internacional atuando principalmente nos seguintes temas: Desenvolvimento Econômico, Economia Política e História do Pensamento Econômico, Economia Internacional, Integração econômica regional e Teoria econômica.",
        photo: "",
    },
    {
        name: "Ana Claudia Andreotti",
        link: "#",
        bio: "Mestre em Políticas Públicas na UFABC.",
        photo: "",
    },
    {
        name: "Bruna Gaudencio Guimarães",
        link: "http://lattes.cnpq.br/4671276183191204",
        bio: "MIT MicroMasters in Data, Economics and Development Policy. Bacharelado em Relações Internacionais e Ciências e Humanidades pela UFABC. Consultora de Analytics e pesquisadora em Biossegurança.",
        photo: "",
    },
    {
        name: "Carlos da Silva dos Santos",
        link: "http://lattes.cnpq.br/5712121407893132",
        bio: "Processamento de Imagens, Reconhecimento de Padrões, Análise de Componentes Independentes, Teoria da Informação.",
        photo: "",
    },
    {
        name: "Diana Maritza Segura Angel",
        link: "http://lattes.cnpq.br/7926761314005188",
        bio: "Doutorado em Ciências pela Universidade de São Paulo, desenvolveu sua pesquisa experimental na multinacional Tongaat Hulett na África do Sul. Áreas de interesse: Sistemas fotovoltaicos, eficiência energética, termodinâmica, física, estatística, análise de dados e mecânica dos fluidos.",
        photo: "",
    },
    {
        name: "Diego Soares Viana de Oliveira",
        link: "http://lattes.cnpq.br/3707731487652877",
        bio: "Doutor em Humanidades pela Universidade de São Paulo, mestre em Filosofia pela Universidade Paris X - Nanterre, economista pela Universidade de São Paulo. Experiência em comunicação social e filosofia das ciências humanas",
        photo: "",
    },
    {
        name: "Eric Ayrão de Castro",
        link: "https://www.linkedin.com/in/eric-ayr%C3%A3o-de-castro-3018bb17a/",
        bio: "Graduando em Ciências Econômicas pela UFRJ e ex-graduando em Engenharia de Controle de Automação também pela UFRJ. Interesse e experiência na área de tratamento e análise de dados.",
        photo: "",
    },
    {
        name: "Fábio Godoy Ferreira",
        link: "http://lattes.cnpq.br/8582022219085253",
        bio: "Mestrando em Engenharia de Energia na UFABC. Experiência na área de análise de dados, machine learning e modelos de planejamento/precificação de energia elétrica.",
        photo: "",
    },
    {
        name: "Fábio Henrique Bittes Terra",
        link: "http://lattes.cnpq.br/2249781288255030",
        bio: "Professor da UFABC e do PPGE-UFU. Pesquisador do CNPq. Pesquisa em macroeconomia, política econômica, teoria econômica e economia brasileira.",
        photo: "",
    },
    {
        name: "Giovanna Arícia Dagel Souza",
        link: "#",
        bio: "Graduanda no Bacharelado em Relações Internacionais pela Universidade Federal do ABC. Apreço e desenvolvimento atual pela área de comunicação digital, especificamente em produção gráfica para redes sociais e design de interfaces.",
        photo: "",
    },
    {
        name: "Guilherme Prado Almeida De Souza",
        link: "http://lattes.cnpq.br/0171085587279213",
        bio: "Mestre em Ciências Humanas e Sociais pela Universidade Federal do ABC na linha de Economia e Desenvolvimento. Áreas de interesse: Economia ecológica, Limites Sociais e Ecológicos do Crescimento, Alternativas Sistêmicas. Constrói o projeto de Economia Solidária Livres Rede de Produção e Consumo Consciente.",
        photo: "",
    },
    {
        name: "Igor Renato Louro Bruno de Abreu",
        link: "https://www.linkedin.com/in/igor-renato-louro-bruno-de-abreu-92228744/",
        bio: "Especializado em cirurgia torácica, em especial tem grande experiência com tumores torácicos. Trabalha em diversos hospitais, em sua maioria no SUS, está na linha de frente desde o início da pandemia (nunca saiu).",
        photo: "",
    },
    {
        name: "João Pedro Loureiro Braga",
        link: "http://lattes.cnpq.br/2481434048339566",
        bio: "Graduando em Ciências Econômicas pela Universidade Federal do Rio de Janeiro (UFRJ). Estuda as áreas de desenvolvimento e desigualdades socioeconômicas, bem-estar e economia chinesa.",
        photo: "",
    },
    {
        name: "José Paulo Guedes Pinto",
        link: "http://lattes.cnpq.br/5483672222004056",
        bio: "Sistemas complexos, crise econômica, ecologia urbana, economia política, economia da colaboração em massa, modelos dinâmicos, propriedade intelectual.",
        photo: "",
    },
    {
        name: "Juliana Santos Oliveira",
        link: "http://lattes.cnpq.br/8906159304582048",
        bio: "Graduanda em Ciências e Humanidades e Ciências Econômicas na Universidade Federal do ABC. Experiência em pesquisa acadêmica nas áreas de Ciência Política e Economia e nas sub áreas de Estado, Democracia, Estado de Bem Estar Social, Política Externa e Finanças Públicas.",
        photo: "",
    },
    {
        name: "Leonardo Freire de Mello",
        link: "http://lattes.cnpq.br/2650858119455746",
        bio: "Planejamento, ambiente e demografia, complexo população-ambiente-consumo, dimensões humanas das mudanças ambientais globais, participação pública nos processos de tomada de decisão.",
        photo: "",
    },
    {
        name: "Leonardo Pinto de Magalhães",
        link: "http://lattes.cnpq.br/8771305776391428",
        bio: "Mestrado em Ciências pela Universidade de São Paulo pelo Programa de Engenharia de Sistemas Agrícolas, atualmente no Doutorado pelo mesmo Programa. Pesquisa na área de Visão Computacional aplicada na agricultura, desenvolve projetos na área de Divulgação Científica e se interessa por Meta-Ciência e Ciência Cidadã.",
        photo: "",
    },
    {
        name: "Lucca Diego Prado",
        link: "https://www.linkedin.com/in/luccap/",
        bio: "Graduando no Bacharelado em Neurociência pela Universidade Federal do ABC (UFABC). Experiência na área de Análise de Dados, Aprendizado de Máquina, Redes Neurais Profundas e Visão Computacional.",
        photo: "",
    },
    {
        name: "Luiz de Siqueira Martins Filho",
        link: "http://lattes.cnpq.br/6177692858000498",
        bio: "Robótica, satélites artificiais, e controle de sistemas dinâmicos.",
        photo: "",
    },
    {
        name: "Maira Begalli",
        link: "http://lattes.cnpq.br/4559907236737788",
        bio: "Doutora em Planejamento e Gestão do Território pela UFABC. Estuda mudanças socioecológicas e ecologia de populações humanas no Antropoceno envolvendo: vulnerabilidade, resiliência e adaptação.",
        photo: "",
    },
    {
        name: "Maria Carolina Maziviero ",
        link: "http://lattes.cnpq.br/8096747745105128",
        bio: "Doutora em Arquitetura e Urbanismo - Fundamentos Sociais do Urbanismo e da Urbanização (FAUUSP). Professora do Departamento de Arquitetura e Urbanismo da Universidade Federal do Paraná (DAU-UFPR).",
        photo: "",
    },
    {
        name: "Pamella Gaiguer Santos",
        link: "https://pamgaiguer.github.io/pamgaiguer/",
        bio: "Bacharel em Sistemas de Informação (Mackenzie/SP). Programação Front-End, UX (User Experience) e UI (User Interface). Responsável pelo desenvolvimento e manutenção do site AçãoCovid19.org",
        photo: "",
    },
    {
        name: "Patrícia Camargo Magalhães",
        link: "http://lattes.cnpq.br/5660309487396721",
        bio: "Pós-Doutoranda na Universidade de Bristol (Inglaterra) com bolsa de pesquisa Marie Curie da União Europeia. Também é vinculada à colaboração LHCb no CERN. Tem experiência na área de Física com ênfase em fenomenologia de Física de Partículas.",
        photo: "",
    },
    {
        name: "Renan da Rosa Bastos",
        link: "http://www.renanbastos.com.br/",
        bio: "Graduado em Tecnologia Análise e Desenvolvimento de Sistemas, amante de tecnologia, inovação e empreendedorismo. Atualmente trabalhando como engenheiro de software.",
        photo: "",
    },
    {
        name: "Rudá Lourenço Cabral Fernandez",
        link: "",
        bio: "Graduando no Bacharelado de Ciência e Tecnologia pela Universidade Federal do ABC, cursando matérias do curso de Engenharia de Gestão. Experiência na área de comunicação por mídias sociais e análise de dados de processos produtivos.",
        photo: "",
    },
    {
        name: "Thales Davi Monea Oliveira",
        link: "",
        bio: "Bacharel em Ciência e Tecnologia e Graduando em Engenharia Aeroespacial pela Universidade Federal do ABC. Estuda modelos de propagadores de Dinâmica de Atitude de Satélites Artificiais.",
        photo: "",
    }
]